/// Local fallback strings (like string resources in Android)
class LocalStrings {
  static const Map<String, String> _strings = {
    "app_name": "AT — Fair Rides NYC",
    // Buttons
    'button_email': 'mail',
    'button_next': 'Next',
    'button_continue': 'Continue',
    'button_continue_with_google': 'Continue with Google',
    'button_continue_with_apple': 'Continue with Apple',
    'button_continue_with_email': 'Continue with Email',
    'button_resend_otp': 'Resend OTP',
    'button_forgot_password': 'I forgot my password',

    // Hints
    'hint_phone_number': 'Phone Number',
    'hint_first_name': 'First Name',
    'hint_last_name': 'Last Name',
    'hint_email_example': 'name@example.com',
    'hint_password': 'Password',
    'hint_otp': 'Enter OTP',
    'button_verify': 'Verify',
    'heading_verify_password': 'Verify Password',
    'heading_verify_your_identity': 'Verify Your Identity',
    'heading_enter_otp': 'Enter OTP',
    'description_enter_your_old_password': 'Please enter your password to verify your identity.',
    'hint_number_example': '(201) 555-0123',
    'hint_enter_password': 'Enter password',
    'hint_confirm_password': 'Confirm Password',

    // Headings
    'heading_what_is_your_name': "What's your name?",
    'heading_accept_terms_and_review_privacy_notice': "Accept {{_APP_NAME}}'s Terms & Review Privacy Notice",
    'heading_legal': 'Legal',
    'description_terms_conditions': 'Terms & Conditions',
    'description_privacy_policy': 'Privacy Policy',
    'heading_what_is_your_email_address': "What's your email address?",
    'heading_create_password': 'Create a password',
    'heading_reset_password': 'Reset your password',
    'heading_verify_account': 'Verify your account',
    'heading_enter_your_mobile_number': 'Enter your mobile number',
    'heading_connecting_nearby_drivers': 'Connecting Nearby Driver',

    // Descriptions
    'description_let_us_know_how_to_properly_address_you': 'Let us know how to properly address you',
    'description_you_will_use_this_number': "You'll use this number to get notifications, sign in, and recover your account.",
    'description_verification_code_send_to_number': 'A verification code will be sent to this number',
    'description_you_will_use_this_email': "You'll use this email to get notifications, sign in, and recover your account.",
    'description_i_agree': 'I Agree',
    'description_agree_terms': 'By selecting "I Agree" below, I have reviewed and agree to the {{_TERMS}} and acknowledge the {{_PRIVACY}}. I am at least 18 years of age.',
    'description_enter_otp_sent_to': 'Enter the {{_LEFT_PARAM}}-digit code sent to {{_RIGHT_PARAM}}',
    'description_resend_phone_code': 'Resend phone code',
    'description_resend_email_code': 'Resend email code',
    'description_email': 'Email',
    'description_phone': 'Phone',
    'description_password': 'Password',
    'description_terms_of_use': 'Terms of Use',
    'description_privacy_notice': 'Privacy Notice',
    'description_changed_your_mobile_number': 'Change your mobile number',
    'description_changed_your_email_address': 'Change your email address',
    'description_login_with_otp_instead': 'Login with OTP instead',
    'description_login_with_password_instead': 'Login with password instead',
    'description_enter_password_for': 'Enter your password for {{_VALUE}}',
    'description_by_continuing_you_agree': "By continuing, you agree to calls, including by autodialer, WhatsApp, or texts from AT and its affiliates. Text \"STOP\" to 89203 to opt out.",

    // Ride Types
    'description_normal': 'Normal',
    'description_share': 'Share',
    'description_rental': 'Rental',
    'description_fix_group_booking': 'Fix Group Booking',

    // Booking Tags
    'description_open_booking': 'Open Booking',
    'description_now': 'Now',
    'description_schedule': 'Schedule',
    'description_bidding': 'Bidding',
    'description_multiple_location': 'Multiple Location',
    'description_fix_fare': 'Fix Fare',
    'description_city_to_city': 'City To City',
    'description_zone': 'Zone',
    'description_airport': 'Airport',
    'description_destination_later': 'Destination Later',
    'description_split_payment': 'Split Payment',
    'description_return': 'Return',
    'description_red_zone': 'Red Zone',
    'description_guest_token': 'Guest Token',
    'description_outside_boundary': 'Outside Boundary',
    'description_weekly': 'Weekly',

    // Referral
    'heading_have_referral_code': 'Have a Referral Code?',
    'heading_referral_policy': 'Referral Policy',
    'hint_referral_code': 'Referral Code (Optional)',
    'error_accept_terms': 'Please accept the terms and conditions',
    'success_referral_code_copied': 'Referral code copied!',
    'button_close': 'Close',

    // Errors
    'error_please_enter_phone_number': 'Please enter phone number',
    'error_please_enter_valid_phone_number': 'Please enter valid phone number',
    'error_please_enter_email': 'Please enter email',
    'error_please_enter_valid_email': 'Please enter valid email',
    'error_please_enter_password': 'Please enter password',
    'error_please_enter_otp': 'Please enter OTP',
    'error_please_enter_valid_first_name': 'Please enter first name',
    'error_please_enter_valid_last_name': 'Please enter last name',
    'error_password_and_confirm_password_must_be_same': 'Password and confirm password must be same',

    // Profile
    'heading_profile': 'Profile',
    'heading_name': 'Name',
    'heading_gender': 'Gender',
    'description_male': 'Male',
    'description_female': 'Female',
    'description_not_set': 'Not set',
    'description_profile_name': 'This is the name other people will see',
    'description_profile_phone': 'A verification code will be sent to this number',
    'description_profile_email': 'A verification code will be sent to this email',
    'button_update': 'Update',

    // Image Picker
    'description_upload_profile': 'In which format would you like to upload your profile?',
    'description_camera': 'Camera',
    'description_image': 'Gallery',
    'description_pdf': 'PDF',
    'button_cancel': 'Cancel',

    // Document
    'heading_document': 'Documents',
    'sub_heading_add': 'Add ',
    'sub_heading_edit': 'Edit ',
    'hint_document_id': 'Document ID',
    'hint_unique_id': 'Unique Code',
    'hint_expiry_date': 'Expiry Date',
    'description_upload_document': 'In which format would you like to upload your document?',
    'description_id_no': 'ID No:',
    'description_exp_date': 'Exp. Date:',
    'description_pending': 'Pending',
    'description_uploaded': 'Uploaded',
    'description_accepted': 'Accepted',
    'description_rejected': 'Rejected',
    'description_doc_expired': 'Expired',
    'description_permission_required': 'Permission required',
    'button_save': 'Save',
    'button_done': 'Done',
    'error_no_document_found': 'No documents found',
    'error_please_document_id': 'Please enter document id',
    'error_please_expiry_date': 'Please enter expiry date',
    'error_please_select_image': 'Please select image',
    'error_please_update_document': 'Please update document',
    'success_document_updated': 'Document updated successfully',
    'error_document_update_failed': 'Failed to update document',

    // Date Picker
    'heading_select_date': 'Select Date',

    // Referral
    'heading_referral': 'Referral',
    'description_invite_your_friend_and_earn_money': 'Invite Your Friend and\nEarn Money',
    'button_view_referral_policy': 'View Referral Policy',
    'description_your_referral_code': 'Your Referral Code',
    'description_tap_to_copy': 'TAP TO COPY',
    'button_refer_your_friend': 'Refer Your Friend',
    'description_share_referral_code': '{{_APP_NAME}}\nUse my referral code: {{_REFERRAL_CODE}}',
    'description_referral_list': 'Referral List',
    'description_no_data_found': 'No data found',

    // Redeem
    'heading_redeem': 'Redeem',
    'heading_redeem_points': 'Redeem Points',
    'button_redeem': 'Redeem',
    'hint_enter_points': 'Enter points to redeem',
    'description_available_points': 'Available Points',
    'description_equivalent': 'Equivalent: {{_VALUE}}',
    'description_available_points_value': 'Available: {{_VALUE}} points',
    'description_balance': 'Balance: {{_VALUE}}',
    'error_no_redeem_history_found': 'Redeem history not found',
    'description_referral_bonus': 'Referral Bonus',
    'description_booking_bonus': 'Booking Bonus',
    'description_review_bonus': 'Review Bonus',
    'description_tip_bonus': 'Tip Bonus',
    'description_daily_booking_accepted_bonus': 'Daily Booking Accepted Bonus',
    'description_daily_booking_completed_bonus': 'Daily Booking Completed Bonus',
    'description_average_rating_bonus': 'Average Rating Bonus',
    'description_reward_point_withdraw': 'Reward Point Withdraw',
    'description_reward_points_value': '{{_REDEEM_POINTS}} points',
    'description_referral_profit_bonus': 'Referral Profit Bonus',
    'description_description_award_profit_bonus': 'Award Profit Bonus',

    // Contact Us / Support / Call
    'button_call': 'Call',
    'button_call_user': 'Call User',
    'button_call_support': 'Call Support',
    'heading_call_user_support': 'Call User / Support',
    'description_thank_you_for_choosing': 'Thank you for choosing {{_APP_NAME}}',
    'heading_contact_us': 'Contact Us',
    'heading_raise_new_ticket': 'Raise New Ticket',
    'heading_ticket_detail': 'Ticket Detail',
    'heading_chat_with_app_name': 'Chat with {{_APP_NAME}} support',
    'description_support_ticket_id': 'Ticket #{{_SUPPORT_ID}}',
    'description_booking_id': 'Booking #{{_UNIT_VALUE}}',
    'description_ticket_open': 'Open',
    'description_ticket_closed': 'Closed',
    'description_ticket_reopen': 'Reopen',
    'description_ticket_cancelled': 'Cancelled',
    'description_select_category': 'Select Category',
    'hint_subject': 'Subject',
    'hint_message': 'Message',
    'button_submit': 'Submit',
    'button_close_ticket': 'Close Ticket',
    'button_reopen_ticket': 'Reopen Ticket',
    'button_raise_new_ticket': 'Raise New Ticket',
    'error_please_select_ticket_category': 'Please select a ticket category',
    'error_please_enter_subject': 'Please enter subject',
    'error_please_select_enter_message': 'Please enter message',
    'description_no_tickets_found': 'No tickets found',

    // Payment
    'error_please_enter_wallet_amount': 'Please enter wallet amount',
    'error_please_select_card': 'Please select card',
    'error_please_enter_card_name': 'Please enter card name',
    'error_please_enter_valid_card_number': 'Please enter valid card number',
    'error_please_enter_valid_expiry_date': 'Please enter valid expiry date',
    'error_please_enter_valid_cvv': 'Please enter valid cvv',
    'error_please_enter_redeem_point': 'Please enter redeem points',
    'error_enter_valid_redeem_point': 'Please enter valid redeem points (minimum {{_VALUE}})',
    'error_user_not_found': 'User not found',
    'heading_payments': 'Payments',
    'heading_delete_card': 'Delete Card',
    'heading_add_card_details': 'Add Card Details',
    'heading_add_wallet_amount': 'Add Wallet Amount',
    'heading_send_money': 'Send Money',
    'heading_select_phone_code': 'Select Phone Code',
    'heading_select_payment_gateway': 'Select Payment Gateway',
    'heading_message_to_your_driver': 'Message to your driver',
    'description_delete_card_message': 'Are you sure you want to delete {{_CARD_NUMBER}} card?',
    'description_customer': 'Customer',
    'description_driver': 'Driver',
    'description_card': 'Card',
    'label_amount': 'Amount',
    'label_phone_number': 'Phone Number',
    'label_select_card': 'Select Card',
    'label_card': 'Card',
    'hint_enter_amount': 'Enter amount',
    'hint_enter_transfer_amount': 'Enter Transfer Amount',
    'hint_card_holder_name': 'Card Holder Name',
    'hint_card_number': 'Card Number',
    'hint_cvv': 'CVV',
    'button_add': 'Add',
    'button_confirm': 'Confirm',
    'button_send': 'Send',
    'button_transfer_money': 'Transfer Money',
    'button_add_new_card': 'Add New Card',
    'sub_heading_payment_methods': 'Payment Methods',

    // No Provider Found
    'heading_no_provider_found': 'No provider found',
    'description_no_provider_found': "We're sorry, there are no nearby drivers available at the moment. We appreciate your business, and we hope you'll check back soon!",

    // Inbox
    'heading_inbox': 'Inbox',

    // Account Menu
    'heading_help': 'Help',
    'heading_wallet': 'Wallet',
    'heading_bookings': 'Bookings',
    'heading_activity': 'Activity',
    'heading_favourites': 'Favourites',
    'button_remove': 'Remove',
    'button_favorite': 'Favorite',
    'description_delete_favourite': 'Are you sure you want to remove this favourite?',
    'button_yes': 'Yes',

    // Settings
    'heading_setting': 'Settings',
    'heading_appearance': 'Appearance',
    'heading_select_language': 'Select Language',
    'heading_delete_account': 'Delete Account',
    'heading_logout': 'Log out',
    'description_add_home': 'Add Home',
    'description_add_work': 'Add Work',
    'description_shortcuts': 'Shortcuts',
    'description_home': 'Home',
    'description_work': 'Work',
    'description_language': 'Language',
    'description_light_mode': 'Light',
    'description_dark_mode': 'Dark',
    'description_system_default': 'System Default',
    'description_delete_account': 'Are you sure you want to delete your account? This action cannot be undone.',
    'description_logout': 'Are you sure you want to log out?',
    'description_delete': 'Delete',
    'description_select_theme': 'Select Theme',
    'description_app_version': 'App Version',

    // Saved Places
    'heading_saved_places': 'Saved places',
    'heading_edit_saved_place': 'Edit saved place',
    'heading_add_saved_place': 'Add a saved place',
    'heading_delete_address': 'Delete address',
    'description_confirm_delete_address_message': 'Are you sure you want to delete this address?',
    'description_saved_place': 'Saved place',
    'description_location_nickname': 'Location nickname',
    'description_address': 'Address',
    'description_getting_address': 'Getting address...',
    'description_move_map_to_select': 'Move map to select location',
    'hint_location_nickname_example': "e.g. Alex's home",
    'hint_search_location': 'Search location',
    'button_add_new_place': 'Add a new place',
    'button_save_place': 'Save place',
    'button_edit': 'Edit',
    'button_set_location_on_map': 'Set location on map',

    // Time
    'description_unit_value': '{{_UNIT_VALUE}} {{_UNIT}}',
    'description_minutes_unit': 'min',

    // Booking Status
    'description_driver_time_estimate': '{{_DRIVER_TIME_ESTIMATE}} away',
    'description_driver_accepted': 'Driver Accepted',
    'description_waiting_time': 'Waiting time',
    'description_free_waiting_time': 'Free waiting time',
    'booking_status_in_route': 'In route',
    'booking_status_arrived_at_pickup': 'Arrived at pickup',
    'booking_status_started': 'Started',
    'booking_status_arrived_at_stop': 'Arrived at Stop',
    'description_arrived_at_your_destination': 'Arrived at your destination',
    'description_pin_for_ride': 'PIN for this ride',

    // Current Ride Screen
    'heading_ride_details': 'Ride Details',
    'sub_heading_ride_details': 'Ride details',
    'button_send_message': 'Send a message',
    'heading_vehicle': 'Vehicle',
    'heading_selected_ride': 'Selected Ride',
    'heading_selected_payment_option': 'Selected Payment Option',
    'description_pickup': 'Pickup',
    'description_stop': 'Stop',
    'description_distance_unit_km': 'km',
    'description_payment': 'Payment',

    // Invoice
    'heading_invoice': 'Invoice',
    'button_view_receipt': 'View Receipt',
    'description_you_need_to_pay_above_amount': 'You need to pay above amount to your driver',
    'button_submit_invoice': 'Submit Invoice',
    'button_pay_by_cash': 'Pay by cash',
    'button_pay': 'Pay',
    'button_pay_again': 'Pay Again',
    'button_cancel_booking': 'Cancel Booking',

    // Receipt
    'description_no_invoice_data': 'No invoice data available',
    'description_receipt_disclaimer': 'This receipt reflects the Suggested Fare only and not a Tax Invoice. However, it can be used for official or reimbursement purposes.',
    'description_thanks_for_riding': 'Thanks for\nriding, {{_CUSTOMER_NAME}}',
    'description_thanks_for_riding_no_name': 'Thanks for\nriding',
    'description_minimum_fare_applied': 'Minimum fare applied',
    'description_subtotal': 'Subtotal',
    'description_total': 'Total',
    'description_free': '\u2022 Free \u2022',

    // Payment Gateways
    'description_cash': 'Cash',
    'description_wallet': 'Wallet',
    'description_stripe': 'Stripe',
    'description_paystack': 'Paystack',
    'description_razorpay': 'Razorpay',
    'description_mercado_pago': 'Mercado Pago',
    'description_payu': 'Payu',
    'description_pago': 'Pago',
    'description_zaincash': 'ZainCash',
    'description_hyperpay': 'Hyperpay',
    'description_nestpay': 'NestPay',
    'description_qicard': 'QiCard',
    'description_mpesa': 'Mpesa',

    // Corporate
    'sub_heading_corporate': 'Corporate',
    'description_would_you_pay_by_corporate': 'Would you like to pay by corporate?',

    // Bidding
    'description_wish_to_bid': 'Wish to Bid?',
    'heading_bid_request': 'Bid Request',
    'description_enter_bid_amount': 'Enter your bid amount',
    'description_your_bid': 'Your Bid',
    'button_confirm_bid': 'Confirm Bid',
    'heading_bidding_request': 'Bidding Request',
    'description_bid_amount_for': 'Bid Amount for',
    'button_accept': 'Accept',
    'button_reject': 'Reject',

    // Booking - From strings.xml
    'button_apply': 'Apply',
    'button_retry': 'Retry',
    'heading_promo_offers': 'Promo Offers',
    'heading_cancellation_policy': 'Cancellation Policy',
    'heading_choose_ride': 'Choose a ride',
    'heading_fare_estimation': 'Fare Estimation',
    'description_drop_off': 'Drop Off',
    'description_destination': 'Destination',
    'description_total_time': 'Total Time',
    'description_total_distance': 'Total Distance',
    'description_stop_time': 'Stop Time',
    'description_free_stop_time': 'Free Stop Time',
    'description_traffic_time': 'Traffic Time',
    'hint_search': 'Search',

    // Booking - New strings
    'heading_confirm_details': 'Confirm details',
    'heading_confirm_pickup_spot': 'Confirm the pickup spot',
    'heading_plan_your_ride': 'Plan your ride',
    'heading_add_stops': 'Add stops',
    'heading_add_a_stop': 'Add a stop',
    'heading_add_stop_on_map': 'Add stop on map',
    'button_confirm_pickup': 'Confirm Pickup',
    'button_confirm_stop': 'Confirm stop',
    'description_apply_promo_code': 'Apply Promo Code',
    'description_promo_applied': 'Promo Applied',
    'description_set_your_pickup_spot': 'Set your pickup spot',
    'description_set_your_destination': 'Set your destination',
    'description_drag_map_to_move_pin': 'Drag map to move pin',
    'description_for_me': 'For me',
    'description_set_pickup': 'Set pickup',
    'description_set_destination': 'Set destination',
    'description_confirm_pickup': 'Confirm pickup',
    'description_confirm_destination': 'Confirm destination',
    'description_pickup_now': 'Pickup now',
    'description_later': 'Later',
    'hint_enter_stop_location': 'Enter stop location',
    'hint_write_notes': 'Write notes',

    // Booking - Error messages
    'error_unable_to_load_vehicles': 'Unable to load vehicles',
    'error_unable_to_load_promo_codes': 'Unable to load promo codes',
    'error_unable_to_load_cancellation_policy': 'Unable to load cancellation policy',
    'error_no_vehicles_available': 'No vehicles available',
    'error_no_vehicles_description': 'Please try again later or select a different ride type',
    'error_no_promo_offers': 'No promo offers available',
    'error_no_cancellation_policy': 'No cancellation policy available',
    'error_no_results_found': 'No results found',

    // Address Validation
    'error_please_enter_pickup_location': 'Please enter pickup location',
    'error_please_enter_valid_pickup_location': 'Please enter a valid pickup location',
    'error_please_enter_drop_off_address': 'Please enter drop off address',
    'error_please_enter_address_title': 'Please enter address title',
    'error_please_enter_address': 'Please enter address',
    'error_pickup_destination_must_be_different': 'Pickup and destination must be different',
    'error_pickup_stop_must_be_different': 'Pickup and stop must be different',
    'error_stop_drop_off_different': 'Stop and drop off must be different',
    'error_consecutive_stop_must_be_different': 'Consecutive stops must be different',
    'error_select_address_from_same_country': 'Please select addresses from the same country',
    'error_please_select_future_time': 'Please select future time',

    // Cancel Trip
    'heading_cancel_trip': 'Cancel trip?',
    'heading_why_do_you_want_to_cancel': 'Why do you want to cancel?',
    'button_keep_my_trip': 'Keep my trip',
    'description_cancel_trip': 'Cancel trip',
    'sub_heading_trip_details': 'Trip details',
    'heading_cancel_booking': 'Cancel Booking',
    'description_are_you_sure_you_want_to_cancel_the_booking': 'Are you sure you want to cancel the booking?',
    'description_cancellation_charge_will_be_applied': '{{_AMOUNT}} cancellation charge will be applied',
    'hint_select_cancellation_reason': 'Select cancellation reason',
    'hint_write_specific_reason': 'Write specific reason',
    'description_others': 'Others',
    'error_please_select_cancellation_reason': 'Please select cancellation reason',
    'error_please_enter_valid_cancellation_reason': 'Please enter valid cancellation reason',

    // Chat
    'description_chat': 'Chat',
    'description_no_messages_yet': 'No messages yet',
    'hint_type_message': 'Type a message...',
    'description_today': 'Today',
    'description_yesterday': 'Yesterday',

    // Activity
    'heading_filter': 'Filter',
    'heading_past': 'Past',
    'heading_upcoming': 'Upcoming',
    'heading_help_and_safety': 'Help & safety',
    'hint_from': 'From',
    'hint_to': 'To',
    'hint_vehicle_color': 'Vehicle Color',
    'button_receipt': 'Receipt',
    'button_re_book': 'Re-Book',
    'button_get_help': 'Get help',
    'button_go_back': 'Go Back',
    'description_no_past_bookings_found': 'No past bookings found',
    'description_no_upcoming_trips': 'You have no upcoming trips',
    'description_reserve_your_ride': 'Reserve your ride \u2192',
    'description_last_seven_days': 'Last 7 days',
    'description_current_month': 'Current month',
    'description_previous_month': 'Previous month',
    'description_previous_six_month': 'Previous 6 months',
    'description_specific_dates': 'Specific Dates',
    'description_distance': 'Distance',
    'description_plate_no': 'Plate No',
    'hint_vehicle_license': 'Vehicle License Number',
    'description_duration': 'Duration',
    'description_cancelled': 'Cancelled',
    'description_rated': 'Rated {{_VALUE}}',
    'description_not_yet_rated': 'Not yet rated',
    'description_driver_rating': 'Driver rating',
    'description_select_reason_for_cancellation': 'Please select a reason for cancellation:',
    'description_ride_with_driver': '{{_LEFT_PARAM}} ride with {{_RIGHT_PARAM}}',
    'description_ride': '{{_VALUE}} ride',
    'description_booking_id_with_separator': 'Booking id \u00b7 {{_UNIT_VALUE}}',
    'description_reason_prefix': 'Reason: {{_VALUE}}',
    'error_please_enter_both_dates': 'Please enter both dates',

    // Feedback
    'heading_feedback': 'Feedback',
    'sub_heading_rate_your_ride_experience': 'How much you rate your ride experience?',
    'sub_heading_comment': 'Comment',
    'hint_write_your_ride_experience': 'Write us your ride experience. We are always happy to hear from you',
    'sub_heading_tip_your_driver': 'Would you like to Tip your Driver',
    'hint_enter_tip_amount': 'Enter tip amount',
    'error_tip_payment_failed': 'Payment failed. Please try again.',
    'description_select_payment_gateway': 'Select Payment Gateway',
    'button_maybe_later': 'Maybe Later',
    'description_rate_awful': 'Awful',
    'description_rate_sad': 'Sad',
    'description_rate_good': 'Good',
    'description_rate_very_good': 'Very Good',
    'description_rate_excellent': 'Excellent',

    // Missing Information
    'sub_heading_missing_information': 'Missing Information',
    'heading_required_actions': 'Required actions',
    'description_book_when_resolved': 'Book a trip when resolved',
    'error_please_update_profile': 'Please update profile',
    'error_please_update_mandatory_document': 'Please upload mandatory document',
    'error_please_select_gender': 'Please select gender',
    'error_not_approved_yet': 'Not approved yet!',
    'error_admin_review_your_document': 'Admin is reviewing your document. Please hold on for sometime',
    'error_admin_doc_rejected': 'Admin has rejected your document. Please re-uploaded your document',
    'error_admin_doc_expired': 'Your document has been expired. Please re-uploaded your document',
    'description_your_account_is_declined': 'Your account is declined. Please\ncontact admin for support',
    'description_your_account_is_blocked': 'Your account is blocked. Please\ncontact admin for support',
    'button_logout': 'Logout',
    'button_contact_us': 'Contact Us',

    // Ride for other
    'heading_new_rider': 'New rider',
    'heading_choose_a_rider': 'Choose a rider',
    'heading_switch_rider': 'Switch rider',
    'description_drivers_will_see_name': 'Drivers will see this name. Do you want to make any changes? ',
    'description_name_change_note': "Changing the name here won't affect how it appears in your device's contacts.",
    'hint_enter_first_name': 'Enter first name',
    'hint_enter_last_name': 'Enter last name',
    'hint_enter_phone_number': 'Enter phone number',
    'description_phone_not_shared': "Phone number won't be shared with drivers",
    'description_add_rider_consent_prefix': 'By tapping ',
    'button_add_rider': 'Add rider',
    'description_add_rider_consent_suffix': ", you confirm that you have this person's permission to send them ride details.",
    'hint_search_name_or_number': 'Search name or number',
    'description_contacts_permission_required': 'Contacts permission is required to choose a rider from your contacts.',
    'button_open_settings': 'Open Settings',
    'button_add_manually': 'Add manually instead',
    'description_frequent_contacts': 'Frequent contacts',
    'description_device_contacts': 'Device contacts',
    'description_no_contacts_found': 'No contacts found',
    'description_no_matching_contacts': 'No matching contacts',
    'description_me': 'Me',
    'button_add_new_contact': 'Add new contact',
    'description_ride_for': 'For {{_USER_NAME}}',

    // App Update
    'heading_we_are_getting_better': "We're Getting Better!",
    'description_app_update': 'Update the App for better experience and bug fixes',
    'button_update_now': 'Update Now!',
    'button_skip_for_now': 'Skip for now',

    // Emergency Contacts
    'heading_add_emergency_contact': 'Add Emergency Contact',
    'heading_update_emergency_contact': 'Update Emergency Contact',
    'sub_heading_emergency_contacts': 'Emergency Contacts',

    // Home Screen
    'app_name_short': 'AT',
    'button_get_a_ride': 'Get a ride',
    'button_share_location': 'Share location',
    'heading_suggestions': 'Suggestions',
    'description_avoid_pickup_confusion': 'Avoid any pickup confusion',

    // Current Ride Screen
    'error_payment_failed': 'Payment Failed',
    'error_payment_unsuccessful': 'Your payment was not successful',

    // Live activity — short time units. Kept local (not server-managed) so the
    // ETA stays compact; the server's unit label is spelled out ("Minutes"),
    // which is too long for the notification / Live Activity rows.
    'live_time_min': 'min',
    'live_time_hr': 'hr',

    // Delivery
    'heading_delivery': 'Delivery',
    'hint_search_restaurants': 'Search for restaurants, dishes & cuisines',
    'description_offers': 'Offers',
    'heading_all_restaurants': 'All Restaurants',
    'description_closed': 'Closed',
    'error_delivery_not_available':
        'Delivery is not available at your location yet.',
    'error_no_restaurants_in_category': 'No restaurants in this category yet.',
    'error_no_restaurants_found': 'No restaurants found near you.',
  };

  /// Get local string by key
  static String getString(String key) {
    return _strings[key] ?? key;
  }
}
